name: RunUNIT1

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Fetch
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile serv.zip
    - name: Extract
      run: |
        Expand-Archive serv.zip
        Rename-Item -Path "serv\ngrok.exe" -NewName "clicon.exe"
    - name: Auth
      run: .\serv\clicon.exe config add-authtoken $Env:AUTH_TOKEN
      env:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    - name: Enable TS
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        Set-LocalUser -Name "installer" -Password (ConvertTo-SecureString -AsPlainText "aaa.123" -Force)
    - name: Start process
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\serv\clicon.exe tcp --region=eu 3389"'
    - name: Unit1 (1/13)
      run: cmd -c "ping localhost -n 3600"
    - name: Unit2 (2/13)
      run: cmd -c "ping localhost -n 3600"
    - name: Unit3 (3/13)
      run: cmd -c "ping localhost -n 3600"
    - name: Unit4 (4/13)
      run: cmd -c "ping localhost -n 3600"
    - name: Unit5 (5/13)
      run: cmd -c "ping localhost -n 3600"
    - name: Unit6 (6/13)
      run: cmd -c "ping localhost -n 3600"
    - name: Unit7 (7/13)
      run: cmd -c "ping localhost -n 3600"
    - name: Unit8 (8/13)
      run: cmd -c "ping localhost -n 3600"
    - name: Unit9 (9/13)
      run: cmd -c "ping localhost -n 3600"
    - name: Unit10 (10/13)
      run: cmd -c "ping localhost -n 3600"
    - name: Unit11 (11/13)
      run: cmd -c "ping localhost -n 3600"
    - name: Unit12 (12/13)
      run: cmd -c "ping localhost -n 3600"
    - name: Unit13 (13/13)
      run: cmd -c "ping localhost -n 3600"
